#!/usr/bin/env bash
# ==============================================================================
# SNAP-AI Remote Deployment Script
# Deploys SNAP-AI on Ubuntu server with NVIDIA GPUs
#
# Usage:
#   chmod +x deploy.sh
#   sudo ./deploy.sh            # Full setup (first time)
#   sudo ./deploy.sh --update   # Update only (pull + restart)
# ==============================================================================

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()   { echo -e "${GREEN}[SNAP-AI]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ==============================================================================
# Pre-flight checks
# ==============================================================================

check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root (sudo ./deploy.sh)"
    fi
}

check_gpu() {
    if command -v nvidia-smi &> /dev/null; then
        log "NVIDIA driver detected:"
        nvidia-smi --query-gpu=name,memory.total --format=csv,noheader
    else
        warn "nvidia-smi not found. Installing NVIDIA drivers..."
        install_nvidia_drivers
    fi
}

# ==============================================================================
# Install dependencies
# ==============================================================================

install_nvidia_drivers() {
    log "Installing NVIDIA drivers..."
    apt-get update
    apt-get install -y linux-headers-$(uname -r)
    apt-get install -y nvidia-driver-535 nvidia-utils-535
    log "NVIDIA drivers installed. Reboot required if this is the first install."
}

install_docker() {
    if command -v docker &> /dev/null; then
        log "Docker already installed: $(docker --version)"
        return
    fi

    log "Installing Docker..."
    apt-get update
    apt-get install -y ca-certificates curl gnupg lsb-release

    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    apt-get update
    apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    systemctl enable docker
    systemctl start docker
    log "Docker installed successfully"
}

install_nvidia_container_toolkit() {
    if dpkg -l | grep -q nvidia-container-toolkit; then
        log "NVIDIA Container Toolkit already installed"
        return
    fi

    log "Installing NVIDIA Container Toolkit..."
    distribution=$(. /etc/os-release; echo $ID$VERSION_ID)
    curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
    curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | \
        sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
        tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

    apt-get update
    apt-get install -y nvidia-container-toolkit
    nvidia-ctk runtime configure --runtime=docker
    systemctl restart docker

    log "NVIDIA Container Toolkit installed"
}

# ==============================================================================
# Configure firewall
# ==============================================================================

setup_firewall() {
    log "Configuring firewall..."
    ufw allow OpenSSH
    ufw allow 80/tcp    # HTTP
    ufw allow 443/tcp   # HTTPS
    ufw --force enable
    log "Firewall configured: SSH, HTTP, HTTPS allowed"
}

# ==============================================================================
# Setup .env file
# ==============================================================================

setup_env() {
    if [[ -f .env ]]; then
        log ".env file already exists (skipping)"
        return
    fi

    log "Creating .env from template..."
    if [[ -f .env.example ]]; then
        cp .env.example .env
    fi

    # Generate secure passwords
    POSTGRES_PW=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)
    REDIS_PW=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)

    cat > .env <<EOF
# SNAP-AI Production Configuration
# Generated by deploy.sh on $(date -Iseconds)

ENVIRONMENT=production

# Database
POSTGRES_DB=snapai
POSTGRES_USER=snapai
POSTGRES_PASSWORD=${POSTGRES_PW}

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=${REDIS_PW}

# LLM
OLLAMA_HOST=http://ollama:11434
OLLAMA_MODEL=me-llama:70b-chat
LLM_BACKEND=ollama
LLM_TEMPERATURE=0.0
LLM_MAX_TOKENS=4096

# Logging
LOG_LEVEL=INFO
EOF

    chmod 600 .env
    log ".env created with secure auto-generated passwords"
    warn "Review and adjust .env settings, especially OLLAMA_MODEL"
}

# ==============================================================================
# Deploy
# ==============================================================================

deploy() {
    log "Deploying SNAP-AI..."

    docker compose -f docker-compose.yml -f docker-compose.remote.yml build --parallel
    docker compose -f docker-compose.yml -f docker-compose.remote.yml up -d

    log "Waiting for services to start..."
    sleep 10

    # Check service health
    log "Service status:"
    docker compose -f docker-compose.yml -f docker-compose.remote.yml ps

    # Verify GPU access
    if docker exec snapai-ollama nvidia-smi &> /dev/null; then
        log "✅ GPU access confirmed in Ollama container"
    else
        warn "⚠️  GPU access could not be verified in Ollama container"
    fi

    log "✅ SNAP-AI deployed successfully!"
    log ""
    log "Access the application at: http://$(hostname -I | awk '{print $1}')"
    log ""
    log "Next steps:"
    log "  1. Pull your desired model:  docker exec snapai-ollama ollama pull me-llama:70b-chat"
    log "  2. Set up SSL if needed (see docs/DEPLOYMENT.md)"
    log "  3. Monitor logs:  docker compose -f docker-compose.yml -f docker-compose.remote.yml logs -f"
}

update() {
    log "Updating SNAP-AI..."
    git pull origin main
    docker compose -f docker-compose.yml -f docker-compose.remote.yml build --parallel
    docker compose -f docker-compose.yml -f docker-compose.remote.yml up -d
    log "✅ Update complete!"
}

# ==============================================================================
# Main
# ==============================================================================

main() {
    check_root

    if [[ "${1:-}" == "--update" ]]; then
        update
        exit 0
    fi

    log "====================================="
    log "SNAP-AI Remote Deployment"
    log "====================================="

    check_gpu
    install_docker
    install_nvidia_container_toolkit
    setup_firewall
    setup_env
    deploy
}

main "$@"
